### PR TITLE
Fix/issue54 multiple example tables

### PR DESCRIPTION
**Pull request by Wayne-Morgan**
This branch addresses issue #54. There were three changes required to fix the issue:

- Fix invocationForScenarioOutline so it uses the appropriate examples table.  example is passed in to the method rather than just taking the first.

- Add tags to the CCIExample class.  Populate the tags from the dictionary provided by the parser.

- Change the filtering in CCIFeaturesManager to respect the examples tags: For any scenario outline which is not excluded, remove any examples which are excluded, and then remove the scenario outline if all examples have been removed.  For any scenario outline which has not been included, remove any examples which have not been included, and then remove the scenario outline if all examples have been removed.

### CODE REVIEW

**Comment by brentleyjones** [comment]
I have a vacation this week. I'll try to review this early next week. Thank you @Wayne-Morgan for your contribution.

**Comment by brentleyjones** [comment]
@Wayne-Morgan In the meantime though, if you want to resolve the merge conflict that would be 💯.

**Comment by Wayne-Morgan** [comment]
Thanks @brentleyjones.  I'll look forward to your feedback.

**Comment by Wayne-Morgan** [comment]
Yeah.  Sorry about that.  My editor is set to remove trailing whitespace, and I didn't realise until after the commit.  Thanks.

**Pull request merged**
