### PR TITLE
Feature/choose directory results

### PR DESCRIPTION
**Pull request by lutzj82**
Allow user to choose a different directory for storing test result output

### CODE REVIEW

**Comment by brentleyjones** [comment]
Hi @lutzj82. Thanks for the contribution. I'm on vacation this week, but I'll try to review this early next week.

**Comment by brentleyjones** [comment]
@Wayne-Morgan In the meantime though, if you want to resolve the merge conflict that would be 💯.

**Comment by Wayne-Morgan** [comment]
Hi @brentleyjones. Did you mean to ask @lutzj82 to resolve these merge conflicts?

**Comment by brentleyjones** [comment]
Sorry, yes! Copy and paste error.

**Comment by brentleyjones** [comment]
@lutzj82 Would you be able to resolve the merge conflicts? After that I'll review this and try to get it merged. Thanks!

**Comment by brentleyjones** [comment]
Thank you @lutzj82 for your contribution!

**Pull request merged**
