### PR TITLE
Add possibility to use emojis in Features

### PR DESCRIPTION
**Pull request by slozo**
* Added NSString category to calculate length for NSRegularExpression
* Added new test example

### CODE REVIEW

**Comment by slozo** [comment]
For our UITests we have to use emojis and with current implementation there was a SIGABRT, becasue calculated range of the string was incorrect for `NSRegularExpression`.

**Comment by plasmabal** [comment]
I started to investigate Cucumberish recently, and it fails on one of our test cases containing Chinese for matching labels.  I can confirm this PR works on my test cases.

However, my fix to my problem is as simple as

```
NSRange searchRange = NSMakeRange(0, step.text.length);
```

in `CCIStepsManager.m`.  I'm not sure if this works for @slozo's situation?

**Comment by Ahmed-Ali** [comment]
Sorry for my late response and thanks @slozo . I will check it out asap.
@plasmabal if possible to open an issue with few example so I can also double check it after merging this PR and apply any needed changes to get it sorted out

**Comment by slozo** [comment]
@plasmabal OMG, why I haven't checked simple `step.text.length`? I guess I was working in Swift playground and there could be a difference? 
@Ahmed-Ali the simplest solution is to use `step.text.length` as @plasmabal suggested. My PR can be discarded.

**Comment by plasmabal** [comment]
Hi @Ahmed-Ali I've created #46 with detailed information.  Hope it helps. :)

**Comment by Ahmed-Ali** [comment]
Thanks guys for your amazing consideration!
I will close this PR now, and make sure to include the fix with the next version.

**Comment by plasmabal** [comment]
@slozo Some of emoji characters seems to think differently about its length, like flags (http://emojipedia.org/flags/), which is two-letter country codes.  That's why I'm not sure if `step.text.length` could fix your problem.  Glad to know the simple solution works. :)

**Comment by slozo** [comment]
@plasmabal I tested it even with different skin tones (for example 👍🏽) and it didn't crash. 
P.S. I still do not believe I didn't check `.length` property ;)

**Pull request closed without merging**
