### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sidekickr**
This request fixes an issue with optionals in a regex. If the optional wasn't present, a test would fail due to a thrown exception. This fixes it and introduces a cucumber feature file for regression testing.

### CODE REVIEW

**Comment by brentleyjones** [comment]
Can you rebase this so it's only your commit? It's showing more changes than what you probably want to merge in.

**Comment by brentleyjones** [comment]
Also, :+1:. I noticed this bug as well, I just didn't get around to looking into it.

**Comment by sidekickr** [comment]
Sure. It looked odd, like there was something that was on master that hadn't moved to develop. I'll take a look.

**Comment by sidekickr** [comment]
I think that the rebase was successful. I had changed 3 files myself and there is a discrepancy in the pod spec between master and develop. Master has it at 1.0.0 and develop at 1.0.

**Comment by Ahmed-Ali** [comment]
Thanks a lot @sidekickr for the contribution. I will check and merge it this weekend.

**Comment by Ahmed-Ali** [comment]
PR merged to develop and is going to master soon.
Thanks man for the help! really appreciated.

**Comment by sidekickr** [comment]
I’ve got another bug fix to submit. I’ll try to get a cleaner commit tree for the pull request.

**Pull request merged**
